### ISSUE TITLE
Timeout Error - Parllama - WSL2

### ISSUE THREAD

**Issue by bamit99** [paulrobello/parllama#8] opened 2024-07-02 10:37 UTC
**Describe the bug**
Getting error when running Parllama with -u option to point to my Ollama instance.

**To Reproduce**

Open Commnd Prompt. Go to WSL
Type parllala -u http://192.168.0.5:11434 to get the error

**Expected behavior**
The application should work.

**Screenshots**
![image](https://github.com/paulrobello/parllama/assets/32737966/b38f2ba3-15c0-4b69-acfd-6cfe9adcd5e4)

**Desktop (please complete the following information):**
 - Windows 11 with WSL2
 - Chrome

**Additional context**

Error:

(parllama) amit@Razor:~/.parllama$ parllama -u http://192.168.0.5:11434
Settings folder /home/amit/.parllama
Traceback (most recent call last):
  File "/home/amit/anaconda3/envs/parllama/bin/parllama", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/parllama/__main__.py", line 21, in run
    ParLlamaApp().run()
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 1624, in run
    asyncio.run(run_app())
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 1610, in run_app
    await self.run_async(
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 1574, in run_async
    await asyncio.shield(app._shutdown())
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 2831, in _shutdown
    await self._close_all()
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 2809, in _close_all
    await self._prune_node(stack_screen)
  File "/home/amit/anaconda3/envs/parllama/lib/python3.11/site-packages/textual/app.py", line 3479, in _prune_node
    raise asyncio.TimeoutError(
TimeoutError: Timeout waiting for [ToastRack(id='textual-toastrack'), Tooltip(id='textual-tooltip'), Header(), Footer(), Static(id='StatusBar'), Static(id='PsStatusBar'), TabbedContent(id='tabbed_content')] to close; possible deadlock (consider changing App.CLOSE_TIMEOUT)

**Comment by paulrobello** [comment] 2024-07-02 15:39
How do you have Ollama installed? Did you use the native windows installer or did you install it via cli inside of WSL?

**Comment by paulrobello** [comment] 2024-07-02 23:04
I just release v0.2.4 which should address all your issues. Please check the WSL section of the Readme.
If it does solve your issue please let me know.

**Comment by bamit99** [comment] 2024-07-03 10:09
I am using Windows Native and it is listening on home PC static IP. Not using DHCP. I have already changed it  using Enviroronment Variables. I am using it with CrewAI\Fabric\MemGPT too hence I know it's working. Let me try some more troubleshooting before connecting back. I will try and take a trace to find the issue.

**Comment by bamit99** [comment] 2024-07-03 11:20
TCPDump shows connections. Ollama Logs shows Get request but no response. It immediately times out with the same above connection.

![image](https://github.com/paulrobello/parllama/assets/32737966/c92e5488-2c76-4a46-b3f0-03f1fea211bd)
![image](https://github.com/paulrobello/parllama/assets/32737966/076db719-e476-490a-8616-df36e9c95363)

**Comment by paulrobello** [comment] 2024-07-03 21:32
another possible way to set the -u option on parllama
```bash
 parllama -u "http://$(grep -m 1 nameserver /etc/resolv.conf | awk '{print $2}'):11434"
 ```

**Comment by bamit99** [comment] 2024-07-04 01:12
Let me try and come back!

**Comment by bamit99** [comment] 2024-07-06 09:35
Same error. I also installed it on Windows machine using Conda Environment. Same issue but different error. Booting another VM right now to test it on a different machine.

![image](https://github.com/paulrobello/parllama/assets/32737966/87faf636-e321-47e8-87c4-6a8f79fd2972)

**Comment by paulrobello** [comment] 2024-07-11 00:55
Latest release v0.3.0 has a lot of reworked internals. Let me know if your issues still persists.
I tested this and the previous version in my WSL without issue.

**Comment by bamit99** [comment] 2024-07-12 07:35
Sure. Let me test and respond back!

**Comment by paulrobello** [comment] 2024-08-06 22:48
Any luck?

**Comment by bamit99** [comment] 2024-08-08 17:40
No but I think this is now more of my machine problem. I could not try a VM But base machine always times out immediately after running command.

**Comment by paulrobello** [comment] 2024-08-08 17:58
Ok, thank you for all your testing. 
As I am unable to reproduce, I am going to close this issue.

**Closed by paulrobello** 2024-08-08 17:58 UTC
Labels: bug
